### ISSUE TITLE
Segmentation fault while trying to extract text from password protected zip file

### ISSUE THREAD

**Issue by tomaszpalasz** [docwire/doctotext#20]
OpenSuse Tumbleweed
Lenovo Y580 / i5-3210M / 16 GB RAM

I created password protected ZIP file (encryption method: AES256/AES192/AES128) using Ark application. ZIP archive contains only one file (Microsoft Word DOC file). When I use text_extractor.sh to extract data from the archive I get following output:
./text_extractor.sh: line 2:  3830 Segmentation fault      (core dumped) LD_LIBRARY_PATH=$BASEDIR:$$LD_LIBRARY_PATH ./$BASEDIR/text_extractor "$@"

**Comment by as-ascii** [comment]
Please keep in mind that this is an experimental version of DecompressArchives chain element that supports ZIP, TAR, RAR, GZ, BZ2 and XZ format. I set 6.0.0 release as a target milestone for analysis and fix of this issue.

**Comment by tomaszpalasz** [comment]
I only tested it using script (text_extractor.sh) on Linux. I will test it on Windows as well and attach results
