### ISSUE TITLE
Replace homebrew with package manager for macOS

### ISSUE THREAD

**Issue by tomaszpalasz** [docwire/doctotext#32]
MacOSX build script uses Homebrew to install quite a lot of 3rdparty libraries. Other dependencies are installed manually via compiling from source code. Unfortunately Homebrew does not have a feature to easily select fixed repository revision and using “latest” version causes unexpected building problems.

**Comment by as-ascii** [comment]
Homebrew was be replaced with VCPKG set to specific fixed revision of package repository for installing required dependencies. Homebrew is only used to install programs like doxygen but compatibility issues are rare in this area.
Vcpkg is a popular free C/C++ package manager for acquiring and managing libraries maintained by the Microsoft C++ team and open source contributors.
